### ISSUE TITLE
Missing gram-class.scm?

### ISSUE THREAD

**Issue by mhatta** [opencog/learn#28]
When I tried to build, it failed with:
```
ERROR: In procedure primitive-load-path:                                        
In procedure primitive-load-path: Unable to find file "opencog/nlp/learn/gram-class.scm" in load path

0% tests passed, 4 tests failed out of 4 
```
Actually, gram-class.scm is not included in learn repo (or any other OpenCog repos AFAIK).

**Comment by linas** [comment]
There is some version skew somewhere ... there used to be a `gram-class.scm` file; it was split in tow and renamed, so now its `./scm/gram-classification.scm` and `./scm/gram-class-api.scm` ...  if I do a `grep -r gram-class.scm`  nothing shows up.  So my guess is that there is some older version installed in your file system (probably in `/usr/local`) that references this now non-existent file.

**Comment by vsbogd** [comment]
It is present in https://github.com/opencog/learn/blob/16b1d7753198bc0df9e033faf3d41b63f08e6b9f/tests/setup.scm#L33
