### ISSUE TITLE
make test is broken

### ISSUE THREAD

**Issue by linas** [opencog/learn#6]
See pull req #4 .. at this time, saying `cmake` causes the system to atempt to run unit tests. This is wrong. I disabled this for now because it breaks the build.  It needs to be fixed.

**Comment by glicerico** [comment]
Interesting... I don't get an attempt to run tests, but only to create the psql databases needed for the tests. Since there is no db management inside opencog (as you mentioned in PR#4), this needs to be done beforehand.
Is this what you're referring to? or actual tests being attempted?

**Comment by linas** [comment]
Can't you set it up so that it only runs when you say `make db` ? 

If you're clever, you can set it up as a dependency for `make test` so that, if the user has never actually run `make db` before, it will do it automatically, before starting the tests.

This file shows an example for testing to see is sql is installed : https://github.com/opencog/atomspace/blob/master/tests/persist/sql/multi-driver/CMakeLists.txt   maybe you can adapt it to intialize the DB.

(what happened for me is that `cmake` errorred out, because it did not have permissions.  So I couldn't run cmake)

**Comment by glicerico** [comment]
Moved db creation to custom target. It isn't triggered automatically yet, but this issue must be solved.

**Comment by linas** [comment]
I looked at it, it seems reasonable. I don't want to test it now, as I've got jobs running.
